modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="jepb" #mandatory
version="1.0.0" #mandatory
displayName="Just Enough Piglin Bartering" #mandatory
authors="thenatekirby" #optional
description='''
Adds JEI support for seeing Piglin Bartering.
'''

[[dependencies.jepb]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.jepb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jepb]]
    modId="babel"
    mandatory=true
    versionRange="[1.0.1,2.0.0)"
    ordering="AFTER"
    side="BOTH"
