modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="jepb" #mandatory
version="1.1.0" #mandatory
displayName="Just Enough Piglin Bartering" #mandatory
authors="thenatekirby" #optional
description='''
Adds JEI support for seeing Piglin Bartering.
'''

[[dependencies.jepb]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.jepb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jepb]]
    modId="babel"
    mandatory=true
    versionRange="[3.0.0,4.0.0)"
    ordering="AFTER"
    side="BOTH"
